### PR TITLE
Add viz delegate schedule

### PR DESCRIPTION
**Pull request by dignityinside**

### CODE REVIEW

**Comment by On1x** [comment]
We must ask @VIM-Arcange to use his code

**Comment by On1x** [comment]
It will be MIT license, if he allowed that :)

**Comment by dignityinside** [comment]
I will try to find contact details to ask him. Hopefully github will send a notification to him, because so far I have not found anything. :-)

**Comment by dignityinside** [comment]
Found his telegram, wrote, waiting for an answer.

**Comment by VIM-Arcange** [comment]
Hello guys. Please apologize for my late reply.
Feel free to reuse the my code.

**Comment by dignityinside** [comment]
@VIM-Arcange thank you for sharing your code.

**Pull request merged**
